import {Metadata} from "next";
import {ErrorWrapper} from "./error-wrapper";

export const metadata:Metadata = {
  title: 
  {
    default:"My Next.js Learning",
    template:"%s | Next.js Mastering",
  },
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <html lang="en">
   <body>
   
   
        <header style={{
          backgroundColor:"lightblue",
          padding:"1.5rem",
        }}
        ><p>Header</p></header>
        <ErrorWrapper>

        {children}
        </ErrorWrapper>

        <footer
        style={{
          backgroundColor:"ghostwhite",
          padding:"1.5rem",
        }}><p>Footer</p></footer>
        </body>
       </html>
  )
}
